name: 'Update Linear Status'
description: 'Updates the status of issues in Linear based on branch names'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  github_token:
    description: 'The token to use to access the GitHub API'
    required: true
  status:
    description: 'The status to set the issue to in Linear'
    required: true
  linear_api_key:
    description: 'API Key for accessing Linear'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'