name: 'Validate PR Title'
description: 'Validates that the PR conforms to semantic naming'

runs:
  using: "composite"
  steps:
    - name: validate PR title
      shell: pwsh
      run: |
        function GetType([string]$value) {
            $validTypes = 'feat', 'fix', 'docs', 'style', 'refactor', 'test', 'chore'
            foreach ($type in $validTypes) {
                if ($value.StartsWith($type)) {
                   return $type
                }
            }
          
            Write-Host "PR Title must start with valid type: $validTypes"
            return $null
        }
        
        function RemoveScope([string] $value) {
            if (!$value.StartsWith("(")) {
                return $value
            }
            
            $endingIndex = $value.IndexOf(")")
            if (-1 -eq $endingIndex) {
                return $value
            }
          
            return $value.Substring($endingIndex + 1)
        }
        
        function RemoveColon([string] $value) {
            $value = $value.Substring(1)
            if ($value.StartsWith(' ')) {
                $value = $value.Substring(1)
            }
          
            return $value
        }
        
        function IsValid ([string]$value) {
            $type = GetType $value
            if ($null -eq $type) {
                return $false
            }
          
            $value = $value.Substring($type.Length)
            $value = RemoveScope $value
          
            if (!$value.StartsWith(":")) {
                Write-Host "PR Title must follow type (and optional scope) with ':'"
                return $false
            }
          
            $value = RemoveColon $value
          
            if (!($value -match '^[a-zA-Z]+-\d+ \S+')) {
                Write-Host "Issue ID must follow type (and optional scope)"
            }
        }
        
        if (!(IsValid {{ github.event.pull_request.title }})) {
            Write-Host "PR Title validation failed"
            exit 1  
        }